---
THRESHOLD: 10
DELTA: 200
writing_pattern:
  memory_write_1:
    Start_time: 0
    Duration: 5
    Start_address: 1
    N: 5
  memory_write_3:
    Start_time: 20
    Duration: 3
    Start_address: 14
    N: 7  
  memory_write_2:
    Start_time: 10
    Duration: 10
    Start_address: 7
    N: 6
  
